### PR TITLE
Workdirs management

### PR DESCRIPTION
**Pull request by Baenshee**
Issues #4 and #8

### CODE REVIEW

**Comment by remyla** [comment]
you are reading the configuration file on every file drop

**Comment by remyla** [comment]
the configuration file should be read at application startup instead of reading it on file drops

**Comment by Baenshee** [comment]
It is read when interactions.js loads, not when files are droped.

**Comment by remyla** [comment]
- the code looks for the conf.json file in /conf.json but I think it was intended to look in the application directory, 'conf.json', without slash
- Your method getWorkdirs() should return the values written in the config file..

**Comment by Baenshee** [comment]
The code looks for conf.json in the static folder. The '/' doesn't change anything.
getWorkdirs() was implemented to get and process the content of localStorage['workdirs'], it is no longer needed. The values in the config file are returned by loadConfJSON().

**Comment by remyla** [comment]
You use getWorkdirs() in the keyboard shortcut you propose. When you prompt "Edit workdirs" to the user, I don't see the workdirs configured in conf.json. Why do you say the '/' doesn't change anything? 'conf.json' looks for a file in the current directory (same as the calling html), while '/conf.json' searches for the file located in the root directory served by the web server

**Comment by Baenshee** [comment]
I just forgot, to update this part, it has been changed in the last commit. (already pushed)
I tested with and without the '/' and it works either way. (with the nodeJs server anyway)
It may be due to the fact that the root directory served by the server is the static folder (in which the conf.json is)

**Comment by remyla** [comment]
Thanks. When the user ask for its workdirs (using the keyboard shortcut you made) he still doesn't see the workdirs configured from the conf file, which I think would be preferred (showing all the configured workdirs to the user is good, else he will never know what has been configured). Showing this will raise the problem which is: having to manage 2 sources for the 'workdirs' value. one source is read-only (the json) and the other is read-write (the localStorage). Anyway I merge your pull request and make an issue so we can move on

**Pull request merged**
